PUT /posts-v1
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "id": { "type": "long" },
      "creator-id": { "type": "long" },
      "creator-name": { "type": "text" },
      "fandom-id": { "type": "long" },
      "fandom-name": { "type": "text" },
      "rubric-id": { "type": "long" },
      "rubric-name": { "type": "text" },
      "activity-id": { "type": "long" },
      "activity-name": { "type": "text" },
      "created": { "type": "date" },
      "language": { "type": "integer" },
      "closed": { "type": "boolean" },
      "comment-count": { "type": "integer" },
      "karma": { "type": "integer" },
      "parent-id": { "type": "integer" },
      "raw_data": {
        "type": "text",
        "index": false
      }
    }
  }
}
