import {
  ArrowLeftIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ClipboardCopyIcon,
  ClipboardIcon,
  ClockIcon,
  DownloadIcon,
  FolderIcon,
  LibraryIcon,
  LockClosedIcon,
  MenuIcon,
  MicrophoneIcon,
  PlusIcon,
  ShareIcon,
  UserCircleIcon,
  UserIcon,
  XIcon
} from "@heroicons/react/solid";

export const icons = {
  0: null,
  1: ArrowLeftIcon,
  2: MenuIcon,
  3: ChevronRightIcon,
  4: ChevronLeftIcon,
  5: DownloadIcon,
  6: ShareIcon,
  7: ChevronUpIcon,
  8: ChevronDownIcon,
  9: ClipboardCopyIcon,
  10: FolderIcon,
  11: ClipboardIcon,
  12: MicrophoneIcon,
  13: XIcon,
  14: LockClosedIcon,
  15: ClockIcon,
  16: LibraryIcon,
  17: UserIcon,
  18: UserCircleIcon,
  19: PlusIcon,
  // TODO
};
