# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'pnpm'
    - name: Setup PNPM
      uses: pnpm/action-setup@v2.0.1
      with:
        version: 6.16.0
        run_install: true
    - run: pnpm run build
    - name: Upload the Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        path: .next/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - uses: actions/checkout@v2
    - name: Download the Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        path: .next/
    - name: ssh deploy
      uses: easingthemes/ssh-deploy@v2.2.11
      with:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.SSH_HOST }}
        REMOTE_USER: root
        SOURCE: .
        TARGET: /opt/campfire-web/
